version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chinchigit/portfolio_portfolio-client:latest

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chinchigit/portfolio_portfolio-server:latest