
  version: '3.8'
  services:
    client:
      build: ./client
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
        - /app/node_modules
      env_file:
        - ./client/.env
    server:
      build: ./server
      ports:
        - "5000:5000"  # Asegúrate de que este puerto esté mapeado correctamente
      volumes:
        - ./server:/app
        - /app/node_modules
      env_file:
        - ./server/.env
    mongo:
      image: mongo
      ports:
        - "27017:27017"