name: Deploy to Railway

on:
  push:
	branches:
	  - ci-cd-deployment   

jobs:
  deploy:
	runs-on: ubuntu-latest

	steps:
	  - name: Check out the repository
		uses: actions/checkout@v2

	  # Configuración de Docker para build y push
	  - name: Log in to Docker Hub
		run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

	  - name: Build Docker images
		uses: docker/compose-action@v2
		with:
		  command: build

	  - name: Push Docker images
		uses: docker/compose-action@v2
		with:
		  command: push

	  # Despliegue a Railway
	  - name: Deploy to Railway
		env:
		  RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
		  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
		run: |
		  railway up --token=$RAILWAY_API_TOKEN --project=$RAILWAY_PROJECT_ID
