name: Deploy to Railway

on:
  push:
    branches:
      - ci/cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Railway Container Registry
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        echo "$RAILWAY_API_TOKEN" | docker login --username=_ --password-stdin registry.railway.app

    - name: Build and push client Docker image
      run: |
        docker build -t registry.railway.app/<RAILWAY_PROJECT_ID>/client ./client
        docker push registry.railway.app/<RAILWAY_PROJECT_ID>/client

    - name: Build and push server Docker image
      run: |
        docker build -t registry.railway.app/<RAILWAY_PROJECT_ID>/server ./server
        docker push registry.railway.app/<RAILWAY_PROJECT_ID>/server

    - name: Release to Railway
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        railway up --project <RAILWAY_PROJECT_ID>